[build] Set macosx deployment target to 10.14 in github action script.
After some package updated, delocate called by cibuildwheel to repair dynamic
library raise error saying:

  delocate.libsana.DelocationError: Library dependencies do not satisfy target MacOS version 10.9:
  .../TAT.cpython-312-darwin.so has a minimum target of 10.14

So we need to set the macosx version in github action build script, which has
already been set in CMakeLists.txt but it is not enough.